title: Mrinal Chandra Sarkar
email: mrinalvbu@gmail.com
description: >-
  Hello world.
baseurl: ""
url: ""
twitter_username: mrinalcs
github_username:  mrinalcs

theme: minima
plugins:
  - jekyll-feed


permalink: /:title

collections:
  pages:
    output: true



exclude:
  - index.html

